# Generated by Django 4.0.3 on 2022-03-13 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentorprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('qualification', models.TextField(max_length=300)),
                ('spicility', models.TextField(max_length=300)),
                ('knowledge', models.TextField(max_length=300)),
                ('experience', models.TextField(max_length=300)),
                ('achivements', models.TextField(max_length=300)),
                ('projects', models.TextField(max_length=300)),
            ],
        ),
    ]
