# Generated by Django 4.0.3 on 2022-03-13 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorprofile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorprofile',
            name='knowledge',
        ),
    ]
