# Generated by Django 4.0.3 on 2022-03-13 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorprofile', '0002_remove_mentorprofile_knowledge'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='contact',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='email',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='knowledge',
            field=models.TextField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
