# Generated by Django 4.0.3 on 2022-03-13 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorprofile', '0003_mentorprofile_contact_mentorprofile_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorprofile',
            name='knowledge',
        ),
    ]
