# Generated by Django 4.0.3 on 2022-03-13 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorprofile', '0004_remove_mentorprofile_knowledge'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='knowledge',
            field=models.TextField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
