# Generated by Django 4.0.3 on 2022-03-13 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.TextField(max_length=100)),
                ('mentor_name', models.TextField(max_length=100)),
                ('mentee_name', models.TextField(max_length=100)),
                ('course_rating', models.IntegerField(max_length=2)),
            ],
        ),
    ]
