# Generated by Django 4.0.3 on 2022-03-13 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menteeprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('interest', models.TextField(max_length=300)),
                ('choosen_Course', models.TextField(max_length=300)),
                ('qualification', models.TextField(max_length=300)),
                ('experience', models.TextField(max_length=300)),
                ('achivements', models.TextField(max_length=300)),
                ('contact', models.IntegerField()),
            ],
        ),
    ]
